// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgGdQOfG_WzNbyDl9L8ysB4rHj411IwB0',
    appId: '1:439382054451:web:770a9eb9f98b4f1326f546',
    messagingSenderId: '439382054451',
    projectId: 'calling-f35c7',
    authDomain: 'calling-f35c7.firebaseapp.com',
    storageBucket: 'calling-f35c7.firebasestorage.app',
    measurementId: 'G-F1Y1KN7PPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGX6PE0SkBJA9QY7maNblDvc50l4PjhDk',
    appId: '1:439382054451:android:02640616f3524c9326f546',
    messagingSenderId: '439382054451',
    projectId: 'calling-f35c7',
    storageBucket: 'calling-f35c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5g2vvwYz-FU8QEtp8qxfFZPOLWOGbOME',
    appId: '1:439382054451:ios:ded81f9fa5442ce926f546',
    messagingSenderId: '439382054451',
    projectId: 'calling-f35c7',
    storageBucket: 'calling-f35c7.firebasestorage.app',
    iosBundleId: 'com.example.calling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5g2vvwYz-FU8QEtp8qxfFZPOLWOGbOME',
    appId: '1:439382054451:ios:ded81f9fa5442ce926f546',
    messagingSenderId: '439382054451',
    projectId: 'calling-f35c7',
    storageBucket: 'calling-f35c7.firebasestorage.app',
    iosBundleId: 'com.example.calling',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgGdQOfG_WzNbyDl9L8ysB4rHj411IwB0',
    appId: '1:439382054451:web:b87b8366e270f56f26f546',
    messagingSenderId: '439382054451',
    projectId: 'calling-f35c7',
    authDomain: 'calling-f35c7.firebaseapp.com',
    storageBucket: 'calling-f35c7.firebasestorage.app',
    measurementId: 'G-7T51Y3KV1V',
  );
}
